# Generated by Django 5.1.7 on 2025-03-07 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_rooms_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='admin_id',
            new_name='admin',
        ),
    ]
